{% set name = "MentaLiST" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://github.com/WGS-TB/MentaLiST/archive/v{{ version }}.tar.gz

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - julia 0.5.2
    - hdf5
    - mpfr
  run:
    - julia 0.5.2
    - hdf5
    - mpfr

test:
  commands:
    - mentalist -h

about:
  home: https://github.com/WGS-TB/MentaLiST
  summary: The MLST pipeline developed by the PathOGiST research group.
  license: MIT
  license_file: LICENSE
