package:
  name: mentalist
  version: "0.0.0"
  
source:
  git_url: https://github.com/WGS-TB/MentaLiST.git
  git_tag: v0.0.0
requirements:
  build:
    - julia
  run:
    - julia

test:

build:
  number: 0
  string: jl_52

about:
  home: https://github.com/WGS-TB/MentaLiST
  license: MIT
  license_file: LICENSE
